language: node_js
node_js:
  - "0.11"
  - "0.10"
before_install:
  - "curl -L https://gist.githubusercontent.com/alexbevi/aec10faff44b698cd419/raw/657567dd485721df25a78f1483091f6a55db1a00/mongo-linter.config.json > config.json"